//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_Librarie.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class achizitie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public achizitie()
        {
            this.linieachizitie = new HashSet<linieachizitie>();
            this.plata = new HashSet<plata>();
        }
    
        public int IdAchizitie { get; set; }
        public int IdFurnizor { get; set; }
        public int NrDocument { get; set; }
        public string SerieDocument { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual furnizor furnizor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<linieachizitie> linieachizitie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plata> plata { get; set; }
    }
}
