//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_Librarie.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartedetaliu
    {
        public int Id { get; set; }
        public string Produs { get; set; }
        public string Titlu { get; set; }
        public string Descriere { get; set; }
        public string ISBN { get; set; }
        public string An { get; set; }
        public string NrPagini { get; set; }
        public string Locatie { get; set; }
        public string Autor { get; set; }
        public string Domeniu { get; set; }
        public string Editura { get; set; }
        public double Pret { get; set; }
        public int Cantitate { get; set; }
    }
}
